/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/addresses/{addressId}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 기본 배송지 설정
         * @description 지정한 배송지를 기본 배송지로 설정합니다.
         */
        put: operations["setDefaultAddress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 신규 사용자를 등록합니다.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 액세스 토큰 재발급
         * @description 리프레시 토큰으로 새 액세스 토큰을 발급합니다.
         */
        post: operations["refreshAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 액세스 토큰을 블랙리스트 처리하고 로그아웃합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/find-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 비밀번호 찾기
         * @description 임시 비밀번호를 발급하고 SMS로 전송합니다.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crowd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 목록 조회
         * @description 전체 프로젝트 목록을 조회합니다.
         */
        get: operations["getAllCrowdFunding"];
        put?: never;
        /**
         * 프로젝트 생성
         * @description 이미지와 프로젝트 정보를 업로드하여 프로젝트를 생성합니다.
         */
        post: operations["createCrowdFunding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crowd/pledges/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 후원 생성
         * @description 프로젝트에 리워드를 선택해 후원합니다.
         */
        post: operations["createPledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bid/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBidding"];
        put?: never;
        /**
         * 입찰 생성
         * @description 특정 경매에 입찰합니다.
         */
        post: operations["createBidding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경매 목록 조회
         * @description 등록된 경매 목록을 조회합니다.
         */
        get: operations["getAllAuctions"];
        put?: never;
        /**
         * 경매 생성
         * @description 이미지와 경매 정보를 업로드하여 경매를 생성합니다.
         */
        post: operations["createAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/unban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 유저 정지 해제
         * @description 유저 계정 정지를 해제합니다.
         */
        post: operations["unbanUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 유저 대상 SMS 전송
         * @description 특정 유저에게 SMS를 전송합니다.
         */
        post: operations["sendSmsToUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/force-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 유저 강제 로그아웃
         * @description 유저의 세션/토큰을 무효화합니다.
         */
        post: operations["forceLogoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 유저 정지
         * @description 유저 계정을 정지 처리합니다.
         */
        post: operations["banUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 임의 번호 SMS 전송
         * @description 전화번호와 메시지를 받아 SMS를 전송합니다.
         */
        post: operations["sendSmsToPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/projects/{projectId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 프로젝트 거절
         * @description 프로젝트를 거절 처리합니다.
         */
        post: operations["rejectProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/projects/{projectId}/force-stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 프로젝트 강제 정지
         * @description 프로젝트를 강제로 중단 처리합니다.
         */
        post: operations["forceStopProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/projects/{projectId}/force-cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 프로젝트 강제 취소
         * @description 프로젝트를 강제로 취소하고 환불 처리합니다.
         */
        post: operations["forceCancelProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/projects/{projectId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 프로젝트 승인
         * @description 프로젝트를 OPEN 상태로 승인합니다.
         */
        post: operations["approveProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/points/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 유저 포인트 조정
         * @description 관리자가 특정 유저의 포인트를 조정합니다.
         */
        post: operations["adjustUserPoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auctions/{auctionId}/force-close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 경매 강제 종료
         * @description 관리자가 경매를 강제로 종료합니다.
         */
        post: operations["forceCloseAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auctions/{auctionId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 경매 취소
         * @description 관리자가 경매를 취소하고 환불 처리합니다.
         */
        post: operations["cancelAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 배송지 목록 조회
         * @description 내 배송지 목록을 조회합니다.
         */
        get: operations["getMyAddresses"];
        put?: never;
        /**
         * 배송지 생성
         * @description 새 배송지를 생성합니다.
         */
        post: operations["createAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 회원정보 수정
         * @description 인증된 사용자의 회원정보를 수정합니다.
         */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/users/update-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 프로필 완성
         * @description 미완성 프로필 정보를 입력해 업데이트합니다.
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/crowd/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 상세 조회
         * @description 특정 프로젝트의 상세 정보를 조회합니다.
         */
        get: operations["getCrowdFunding"];
        put?: never;
        post?: never;
        /**
         * 프로젝트 삭제
         * @description 본인 프로젝트를 삭제합니다.
         */
        delete: operations["deleteCrowdFunding"];
        options?: never;
        head?: never;
        /**
         * 프로젝트 수정
         * @description 본인 프로젝트 정보를 수정합니다.
         */
        patch: operations["updateCrowdFunding"];
        trace?: never;
    };
    "/api/crowd/pledges/{pledgeId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 후원 취소
         * @description 내 후원을 취소합니다.
         */
        patch: operations["cancelPledge"];
        trace?: never;
    };
    "/api/addresses/{addressId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 배송지 상세 조회
         * @description 내 특정 배송지를 조회합니다.
         */
        get: operations["getAddress"];
        put?: never;
        post?: never;
        /**
         * 배송지 삭제
         * @description 내 배송지를 삭제합니다.
         */
        delete: operations["deleteAddress"];
        options?: never;
        head?: never;
        /**
         * 배송지 수정
         * @description 내 배송지를 수정합니다.
         */
        patch: operations["updateAddress"];
        trace?: never;
    };
    "/api/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로필 조회
         * @description 내 프로필 정보를 조회합니다.
         */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/my-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 마이페이지 조회
         * @description 내 마이페이지 정보를 조회합니다.
         */
        get: operations["getMyPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["autoComplete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projectSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/project/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auctionSearchFilter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/auction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auctionSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/auction/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auctionSearchFilter_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crowd/pledges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 후원 목록 조회
         * @description 내 후원 내역 전체를 조회합니다.
         */
        get: operations["getMyPledges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auction/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경매 상세 조회
         * @description 특정 경매의 상세 정보를 조회합니다.
         */
        get: operations["getAuction"];
        put?: never;
        post?: never;
        /**
         * 경매 삭제
         * @description 본인이 등록한 경매를 삭제합니다.
         */
        delete: operations["deleteAuction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 유저 목록 조회
         * @description 검색 조건과 페이징으로 유저 목록을 조회합니다.
         */
        get: operations["getUserList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 유저 상세 조회
         * @description 유저 기본 정보와 활동 내역을 조회합니다.
         */
        get: operations["getUserDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 유저 포인트 히스토리 조회
         * @description 특정 유저의 포인트 변경 이력을 조회합니다.
         */
        get: operations["getUserPointHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sellers/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 판매자 상세 조회
         * @description 판매자의 기본 정보와 등록한 경매/프로젝트 목록을 조회합니다.
         */
        get: operations["getSellerDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 목록 조회
         * @description 검색 조건과 페이징으로 프로젝트 목록을 조회합니다.
         */
        get: operations["getProjectList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 프로젝트 상세 조회
         * @description 프로젝트, 리워드, 후원 내역을 조회합니다.
         */
        get: operations["getProjectDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경매 목록 조회
         * @description 검색 조건과 페이징으로 경매 목록을 조회합니다.
         */
        get: operations["getAuctionList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경매 상세 조회
         * @description 특정 경매의 상세 정보를 조회합니다.
         */
        get: operations["getAuctionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addresses/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 기본 배송지 조회
         * @description 내 기본 배송지를 조회합니다.
         */
        get: operations["getDefaultAddress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴
         * @description 인증된 사용자 계정을 삭제합니다.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserRequestDto: {
            email: string;
            password: string;
            username: string;
            nickname: string;
            phoneNumber: string;
            account?: string;
            accountHolder?: string;
            /** @enum {string} */
            bankType?: "KAKAO" | "NH" | "KB" | "SHINHAN" | "WOORI" | "SAEMAEUL" | "BUSAN" | "IBK" | "TOSS" | "etc";
        };
        FindPasswordRequestDto: {
            email?: string;
            username?: string;
        };
        ProjectRequestDto: {
            title: string;
            description: string;
            /** Format: int64 */
            targetAmount: number;
            /** Format: date */
            startAt: string;
            /** Format: date */
            endAt: string;
            categoryPath?: string;
            tags?: string;
            summary?: string;
            rewardTiers: components["schemas"]["RewardTierRequestDto"][];
            /** Format: int32 */
            mainIndex?: number;
        };
        RewardTierRequestDto: {
            title: string;
            description: string;
            /** Format: int64 */
            price: number;
            /** Format: int64 */
            limitQuantity?: number;
        };
        PledgeCreateRequestDto: {
            items: components["schemas"]["PledgeItemDto"][];
        };
        PledgeItemDto: {
            /** Format: int64 */
            rewardTierId: number;
            /** Format: int32 */
            quantity: number;
        };
        PledgeCreateResponseDto: {
            /** Format: int64 */
            projectId?: number;
            orderId?: string;
            /** Format: int64 */
            totalAmount?: number;
            items?: components["schemas"]["PledgeItemResultDto"][];
            /** Format: date-time */
            createdAt?: string;
        };
        PledgeItemResultDto: {
            /** Format: int64 */
            pledgeId?: number;
            /** Format: int64 */
            rewardTierId?: number;
            /** Format: int64 */
            quantity?: number;
            /** Format: int64 */
            amount?: number;
            /** @enum {string} */
            status?: "PENDING" | "PAID" | "REFUND" | "CONFIRMED" | "SHIPPED" | "CANCELED";
        };
        BidsRequestDto: {
            /** Format: int64 */
            price?: number;
        };
        AuctionRequestDto: {
            title?: string;
            description?: string;
            /** Format: int64 */
            startPrice?: number;
            /** Format: int32 */
            bidStep?: number;
            endAt?: string;
            /** Format: int32 */
            mainIndex?: number;
        };
        SmsToPhoneRequestDto: {
            phoneNumber?: string;
            message?: string;
        };
        AdjustPointRequestDto: {
            /** Format: int64 */
            userId?: number;
            /** Format: int64 */
            adjustPoint?: number;
            reason?: string;
        };
        AddressCreateRequestDto: {
            label?: string;
            recipientName: string;
            phone: string;
            zipCode: string;
            address1: string;
            address2: string;
            setAsDefault?: boolean;
        };
        UserUpdateRequestDto: {
            email: string;
            password: string;
            username: string;
            nickname: string;
            phoneNumber: string;
            account?: string;
            accountHolder?: string;
            /** @enum {string} */
            bankType?: "KAKAO" | "NH" | "KB" | "SHINHAN" | "WOORI" | "SAEMAEUL" | "BUSAN" | "IBK" | "TOSS" | "etc";
        };
        ProfileRequestDto: {
            username: string;
            nickname: string;
            phoneNumber: string;
        };
        ProjectUpdateRequestDto: {
            title?: string;
            description?: string;
            /** Format: int64 */
            targetAmount?: number;
            /** Format: date */
            startAt?: string;
            /** Format: date */
            endAt?: string;
            categoryPath?: string;
            tags?: string;
            summary?: string;
            rewardTiers?: components["schemas"]["RewardTierRequestDto"][];
            deleteImageIds?: number[];
            /** Format: int32 */
            mainIndex?: number;
            /** Format: int64 */
            mainImageId?: number;
        };
        AddressUpdateRequestDto: {
            label?: string;
            recipientName: string;
            phone: string;
            zipCode: string;
            address1: string;
            address2: string;
            setAsDefault?: boolean;
        };
        SearchAutoCompleteResponse: {
            title?: string;
        };
        ProjectSearchResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            thumbnailUrl?: string;
            /** Format: int64 */
            targetAmount?: number;
            /** Format: int64 */
            currentAmount?: number;
            status?: string;
            /** Format: date */
            startAt?: string;
            /** Format: date */
            endAt?: string;
        };
        PageProjectSearchResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ProjectSearchResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        SortObject: {
            empty?: boolean;
            unsorted?: boolean;
            sorted?: boolean;
        };
        AuctionSearchResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            imageKey?: string;
            seller?: string;
            description?: string;
            /** Format: int64 */
            startPrice?: number;
            /** Format: int64 */
            currentPrice?: number;
            status?: string;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
        };
        PageAuctionSearchResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AuctionSearchResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        CreatorDto: {
            /** Format: int64 */
            creatorId?: number;
            email?: string;
            nickname?: string;
        };
        ProjectResponseDto: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            thumbnailUrl?: string;
            /** Format: int64 */
            targetAmount?: number;
            /** Format: int64 */
            currentAmount?: number;
            /** @enum {string} */
            status?: "DRAFT" | "OPEN" | "SUCCESS" | "FAILED" | "CANCELED" | "REJECTED" | "STOP";
            /** Format: date */
            startAt?: string;
            /** Format: date */
            endAt?: string;
            categoryPath?: string;
            tags?: string;
            summary?: string;
            creator?: components["schemas"]["CreatorDto"];
            /** Format: int32 */
            achievementRate?: number;
        };
        ProjectDetailResponseDto: {
            /** Format: int64 */
            id?: number;
            creator?: components["schemas"]["CreatorDto"];
            title?: string;
            description?: string;
            thumbnailUrl?: string;
            /** Format: int64 */
            targetAmount?: number;
            /** Format: int64 */
            currentAmount?: number;
            /** @enum {string} */
            status?: "DRAFT" | "OPEN" | "SUCCESS" | "FAILED" | "CANCELED" | "REJECTED" | "STOP";
            /** Format: date */
            startAt?: string;
            /** Format: date */
            endAt?: string;
            categoryPath?: string;
            tags?: string;
            summary?: string;
            rewardTiers?: components["schemas"]["RewardTierResponseDto"][];
            images?: components["schemas"]["ProjectImageResponseDto"][];
            /** Format: int32 */
            achievementRate?: number;
        };
        ProjectImageResponseDto: {
            /** Format: int64 */
            id?: number;
            key?: string;
        };
        RewardTierResponseDto: {
            /** Format: int64 */
            rewardTierId?: number;
            title?: string;
            description?: string;
            /** Format: int64 */
            price?: number;
            /** Format: int64 */
            limitQuantity?: number;
            /** Format: int64 */
            soldQuantity?: number;
            soldOut?: boolean;
        };
        AuctionImageResponseDto: {
            /** Format: int64 */
            id?: number;
            key?: string;
        };
        AuctionResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            title?: string;
            description?: string;
            mainImageKey?: string;
            seller?: components["schemas"]["UserResponseDto"];
            winner?: components["schemas"]["UserResponseDto"];
            /** Format: int64 */
            startPrice?: number;
            /** Format: int64 */
            currentPrice?: number;
            /** Format: int32 */
            bidStep?: number;
            /** @enum {string} */
            auctionStatus?: "RUNNING" | "ENDED" | "CANCELED";
            images?: components["schemas"]["AuctionImageResponseDto"][];
            /** Format: date-time */
            startAt?: string;
            endAt?: string;
        };
        UserResponseDto: {
            /** Format: int64 */
            id?: number;
            email?: string;
            username?: string;
            nickname?: string;
            phoneNumber?: string;
            account?: string;
            accountHolder?: string;
            /** @enum {string} */
            role?: "USER" | "ADMIN";
            /** Format: int64 */
            pointBalance?: number;
            /** @enum {string} */
            bankType?: "KAKAO" | "NH" | "KB" | "SHINHAN" | "WOORI" | "SAEMAEUL" | "BUSAN" | "IBK" | "TOSS" | "etc";
            active?: boolean;
        };
        AuctionDetailResponseDto: {
            /** Format: int64 */
            auctionId?: number;
            title?: string;
            description?: string;
            seller?: components["schemas"]["UserResponseDto"];
            winner?: components["schemas"]["UserResponseDto"];
            /** Format: int64 */
            startPrice?: number;
            /** Format: int64 */
            currentPrice?: number;
            /** Format: int32 */
            bidStep?: number;
            /** @enum {string} */
            auctionStatus?: "RUNNING" | "ENDED" | "CANCELED";
            images?: components["schemas"]["AuctionImageResponseDto"][];
            /** Format: date-time */
            startAt?: string;
            endAt?: string;
            bids?: components["schemas"]["BidsResponseDto"][];
        };
        BidsResponseDto: {
            /** Format: int64 */
            id?: number;
            user?: components["schemas"]["UserResponseDto"];
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            price?: number;
        };
        AdminUserSearchCondition: {
            email?: string;
            username?: string;
            nickname?: string;
            phoneNumber?: string;
            /** @enum {string} */
            role?: "USER" | "ADMIN";
            active?: boolean;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        AdminUserSummaryDto: {
            /** Format: int64 */
            id?: number;
            email?: string;
            username?: string;
            nickname?: string;
            phoneNumber?: string;
            provider?: string;
            role?: string;
            active?: boolean;
            /** Format: int64 */
            pointBalance?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        PageAdminUserSummaryDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AdminUserSummaryDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        AdminBidSummaryDto: {
            /** Format: int64 */
            bidId?: number;
            /** Format: int64 */
            userId?: number;
            username?: string;
            /** Format: int64 */
            auctionId?: number;
            /** Format: int64 */
            price?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        AdminPledgeSummaryDto: {
            /** Format: int64 */
            pledgeId?: number;
            orderId?: string;
            /** Format: int64 */
            projectId?: number;
            /** Format: int64 */
            rewardTierId?: number;
            /** Format: int64 */
            paidAmount?: number;
            /** Format: int64 */
            quantity?: number;
            /** @enum {string} */
            status?: "PENDING" | "PAID" | "REFUND" | "CONFIRMED" | "SHIPPED" | "CANCELED";
            /** Format: date-time */
            createdAt?: string;
        };
        AdminPointHistoryRepDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            username?: string;
            nickname?: string;
            /** Format: int64 */
            changeAmount?: number;
            /** Format: int64 */
            balanceAfter?: number;
            type?: string;
            source?: string;
            /** Format: int64 */
            referenceId?: number;
            description?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        AdminUserDetailDto: {
            user?: components["schemas"]["AdminUserSummaryDto"];
            bids?: components["schemas"]["AdminBidSummaryDto"][];
            pledges?: components["schemas"]["AdminPledgeSummaryDto"][];
            pointHistories?: components["schemas"]["AdminPointHistoryRepDto"][];
        };
        PageAdminPointHistoryRepDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AdminPointHistoryRepDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        AdminAuctionSummaryDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            sellerId?: number;
            sellerUsername?: string;
            /** Format: int64 */
            currentWinnerId?: number;
            currentWinnerUsername?: string;
            title?: string;
            /** Format: int64 */
            startPrice?: number;
            /** Format: int64 */
            currentPrice?: number;
            /** Format: int32 */
            bidStep?: number;
            auctionStatus?: string;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        AdminProjectSummaryDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            creatorId?: number;
            title?: string;
            summary?: string;
            /** Format: int64 */
            targetAmount?: number;
            /** Format: int64 */
            currentAmount?: number;
            status?: string;
            /** Format: date */
            startAt?: string;
            /** Format: date */
            endAt?: string;
            thumbnailUrl?: string;
            categoryPath?: string;
            tags?: string;
            /** Format: int64 */
            likeCount?: number;
            /** Format: int64 */
            totalPledgeCount?: number;
            /** Format: double */
            achievementRate?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        AdminSellerDetailDto: {
            seller?: components["schemas"]["AdminUserSummaryDto"];
            auctions?: components["schemas"]["AdminAuctionSummaryDto"][];
            projects?: components["schemas"]["AdminProjectSummaryDto"][];
        };
        AdminProjectSearchCondition: {
            title?: string;
            creatorEmail?: string;
            creatorUsername?: string;
            status?: string;
            categoryPath?: string;
            /** Format: date */
            startFrom?: string;
            /** Format: date */
            startTo?: string;
        };
        PageAdminProjectSummaryDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AdminProjectSummaryDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        AdminProjectDetailDto: {
            project?: components["schemas"]["AdminProjectSummaryDto"];
            rewardTiers?: components["schemas"]["AdminRewardTierSummaryDto"][];
            pledges?: components["schemas"]["AdminPledgeSummaryDto"][];
        };
        AdminRewardTierSummaryDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            projectId?: number;
            title?: string;
            description?: string;
            /** Format: int64 */
            price?: number;
            /** Format: int64 */
            limitQuantity?: number;
            /** Format: int64 */
            soldQuantity?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        AdminAuctionSearchCondition: {
            title?: string;
            sellerUsername?: string;
            status?: string;
            /** Format: date-time */
            startFrom?: string;
            /** Format: date-time */
            startTo?: string;
        };
        PageAdminAuctionSummaryDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AdminAuctionSummaryDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        AdminAuctionDetailDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            sellerId?: number;
            sellerUsername?: string;
            /** Format: int64 */
            winnerId?: number;
            winnerUsername?: string;
            /** Format: int64 */
            currentWinnerId?: number;
            currentWinnerUsername?: string;
            title?: string;
            description?: string;
            /** Format: int64 */
            startPrice?: number;
            /** Format: int64 */
            currentPrice?: number;
            /** Format: int32 */
            bidStep?: number;
            auctionStatus?: string;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            /** Format: date-time */
            createdAt?: string;
            bids?: components["schemas"]["AdminBidSummaryDto"][];
        };
        AddressResponseDto: {
            /** Format: int64 */
            id?: number;
            label?: string;
            recipientName?: string;
            phoneNumber?: string;
            zipCode?: string;
            address1?: string;
            address2?: string;
            default?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setDefaultAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 설정 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 설정 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 배송지를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequestDto"];
            };
        };
        responses: {
            /** @description 회원가입 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 요청 값 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    refreshAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 재발급 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 리프레시 토큰 유효하지 않음 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindPasswordRequestDto"];
            };
        };
        responses: {
            /** @description 발급 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getAllCrowdFunding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponseDto"][];
                };
            };
        };
    };
    createCrowdFunding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    data: components["schemas"]["ProjectRequestDto"];
                    file: string[];
                };
            };
        };
        responses: {
            /** @description 생성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 요청 값 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    createPledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PledgeCreateRequestDto"];
            };
        };
        responses: {
            /** @description 후원 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PledgeCreateResponseDto"];
                };
            };
            /** @description 요청 값 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PledgeCreateResponseDto"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PledgeCreateResponseDto"];
                };
            };
            /** @description 프로젝트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PledgeCreateResponseDto"];
                };
            };
        };
    };
    getBidding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    createBidding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidsRequestDto"];
            };
        };
        responses: {
            /** @description 입찰 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 요청 값 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 경매를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getAllAuctions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuctionResponseDto"][];
                };
            };
        };
    };
    createAuction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    file: string[];
                    data: components["schemas"]["AuctionRequestDto"];
                };
            };
        };
        responses: {
            /** @description 생성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 요청 값 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    unbanUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 해제 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendSmsToUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description 전송 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forceLogoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description 강제 로그아웃 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    banUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description 정지 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendSmsToPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmsToPhoneRequestDto"];
            };
        };
        responses: {
            /** @description 전송 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 요청 값 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejectProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description 거절 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forceStopProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description 정지 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forceCancelProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description 취소 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approveProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 승인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 프로젝트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adjustUserPoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustPointRequestDto"];
            };
        };
        responses: {
            /** @description 조정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forceCloseAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description 강제 종료 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 경매를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description 취소 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 경매를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMyAddresses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponseDto"][];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponseDto"][];
                };
            };
        };
    };
    createAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressCreateRequestDto"];
            };
        };
        responses: {
            /** @description 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
            /** @description 요청 값 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": number;
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequestDto"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 요청 값 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequestDto"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 요청 값 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getCrowdFunding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetailResponseDto"];
                };
            };
            /** @description 프로젝트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDetailResponseDto"];
                };
            };
        };
    };
    deleteCrowdFunding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 삭제 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 프로젝트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    updateCrowdFunding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    data: components["schemas"]["ProjectUpdateRequestDto"];
                    file?: string[];
                };
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 요청 값 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 수정 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 프로젝트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    cancelPledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pledgeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 취소 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 취소 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 후원을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponseDto"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponseDto"];
                };
            };
            /** @description 조회 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponseDto"];
                };
            };
            /** @description 배송지를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponseDto"];
                };
            };
        };
    };
    deleteAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 삭제 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 배송지를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressUpdateRequestDto"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 요청 값 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 수정 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 배송지를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getMyPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    autoComplete: {
        parameters: {
            query: {
                keyword: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchAutoCompleteResponse"][];
                };
            };
        };
    };
    projectSearch: {
        parameters: {
            query: {
                title: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectSearchResponse"][];
                };
            };
        };
    };
    auctionSearchFilter: {
        parameters: {
            query?: {
                title?: string;
                endAt?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageProjectSearchResponse"];
                };
            };
        };
    };
    auctionSearch: {
        parameters: {
            query: {
                title: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuctionSearchResponse"][];
                };
            };
        };
    };
    auctionSearchFilter_1: {
        parameters: {
            query?: {
                title?: string;
                endAt?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAuctionSearchResponse"];
                };
            };
        };
    };
    getMyPledges: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PledgeCreateResponseDto"][];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PledgeCreateResponseDto"][];
                };
            };
        };
    };
    getAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuctionDetailResponseDto"];
                };
            };
            /** @description 경매를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuctionDetailResponseDto"];
                };
            };
        };
    };
    deleteAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 삭제 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description 경매를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    getUserList: {
        parameters: {
            query: {
                condition: components["schemas"]["AdminUserSearchCondition"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminUserSummaryDto"];
                };
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminUserSummaryDto"];
                };
            };
        };
    };
    getUserDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminUserDetailDto"];
                };
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminUserDetailDto"];
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminUserDetailDto"];
                };
            };
        };
    };
    getUserPointHistory: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminPointHistoryRepDto"];
                };
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminPointHistoryRepDto"];
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminPointHistoryRepDto"];
                };
            };
        };
    };
    getSellerDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSellerDetailDto"];
                };
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSellerDetailDto"];
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSellerDetailDto"];
                };
            };
        };
    };
    getProjectList: {
        parameters: {
            query: {
                condition: components["schemas"]["AdminProjectSearchCondition"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminProjectSummaryDto"];
                };
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminProjectSummaryDto"];
                };
            };
        };
    };
    getProjectDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProjectDetailDto"];
                };
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProjectDetailDto"];
                };
            };
            /** @description 프로젝트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProjectDetailDto"];
                };
            };
        };
    };
    getAuctionList: {
        parameters: {
            query: {
                condition: components["schemas"]["AdminAuctionSearchCondition"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminAuctionSummaryDto"];
                };
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminAuctionSummaryDto"];
                };
            };
        };
    };
    getAuctionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminAuctionDetailDto"];
                };
            };
            /** @description 관리자 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminAuctionDetailDto"];
                };
            };
            /** @description 경매를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminAuctionDetailDto"];
                };
            };
        };
    };
    getDefaultAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponseDto"];
                };
            };
            /** @description 기본 배송지 없음 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponseDto"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AddressResponseDto"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
}
